### ISSUE TITLE
OSWSWinProcess new  cannot run #command: under P13/MSWindows

### ISSUE THREAD

**Issue by riuttner** [pharo-contributions/OSWinSubprocess#7]
Found your nice contribution and tried it under P13 (latest release) for Windows running your example: 
```
OSWSWinProcess new 
		command: 'C:\Windows\notepad.exe';
		runAndWait.
```
First of all, I got a missing subclass responsibility of `OSWSWinProcessLibrary` which I tried to fix as follows:
```
win32LibraryName
	^ FFIWindowsLibraryFinder findAnyLibrary: #('Kernel32.dll')
```
assuming that 'Kernel32.dll' should contain what is needed and further assuming that the library finder should be used. But then the code failed because of an unresolved FFI reference to `memset` called by `OSWSWinProcessLibrary`. When looking around the code in this class I detected an unsent message:
```
win32ModuleName
	^ 'msvcrt.dll'
```
My next guess was to implement #win32LibraryName in the same way, and since then it worked :) - in my tests also when using the `FFIWindowsLibraryFinder` looking for  'msvcrt.dll' instead of returning the string directly.

Thus I cannot tell what would be the intended way to fix this little bug according to the rules for Pharo13 and ask you kindly to fix it occasionally - because that seems to be the only small issue keeping somebody from using your contribution under Windows (even though I have not tested more than the #command: call up to now).

**Comment by demarey** [comment]
Hi Richard,

Thanks a lot for finding this issue and reporting it.
You're right, `win32ModuleName` was deprecated in favor of `win32LibraryName`. You did the right fix.
Sorry, it took me a while to find a Windows machine to test it.
I will commit the fix ASAP.

**Comment by riuttner** [comment]
Hi Christophe,
many thanks for the fix - unfortunately not all issues are that easy to solve ;) ... but it's nice that your contribution is ready for use again!
